# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 清泉
SEOTitle: Johnny的博客 | johnny Blog
email: johnny@clspring.com
description: > # this means to ignore newlines until "baseurl:"
  室内定位（UWB），zephyr 学习者，菜鸟级嵌入式程序员。感谢jekyll提供的博客框架!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://clspring.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  J1207808305

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写写代码，做做设计，<br>离开世界之前，一切都是过程"
sidebar-avatar:                         #你的大头贴，请使用绝对地址.
                                        
# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value
